INSERT INTO
  users(
    first_name,
    last_name,
    username,
    email,
    user_zip_code,
    avatar_url,
    user_type,
    password
  )
VALUES
  (
    'Mario',
    'Bros',
    'MariB',
    'mario@nintendo.com',
    '',
    'https://i.imgur.com/LpaY82x.png',
    true,
    'password'
  ),
  (
    'Luigi',
    'Bros',
    'LuiB',
    'luigi@nintendo.com',
    'K2P 1L8',
    'https://i.imgur.com/Nmx0Qxo.png',
    false,
    'password'
  ),
  (
    'Princess',
    'Peach',
    'PriP',
    'peach@nintendo.com',
    '',
    'https://i.imgur.com/T2WwVfS.png',
    true,
    'password'
  ),
  (
    'Princess',
    'Daisy',
    'Pdaisy',
    'daisy@nintendo.com',
    'K1N 9J7',
    'https://i.imgur.com/FK8V841.jpg',
    false,
    'password'

  ),
  ('Donkey',
  'Kong',
  'DonK',
  'donkey@nintendo.com',
  '',
  'https://i.imgur.com/twYrpay.jpg',
  true,
  'password'
  );