INSERT INTO
  users(
    first_name,
    last_name,
    username,
    email,
    user_zip_code,
    avatar_url,
    user_type,
    password
  )
VALUES
  (
    'Mario',
    'Bros',
    'MariB',
    'mario@nintendo.com',
    '',
    'images/avatars/avatar-4.png',
    true,
    '$2b$10$MhKTEmeJTB/Q2YbqLd7uXejgByEuIBb7p0Gy4huu6ktKLNZl38JxC'
  ),
  (
    'Luigi',
    'Bros',
    'LuiB',
    'luigi@nintendo.com',
    'K2P 1L8',
    'images/avatars/avatar-1.png',
    false,
    '$2b$10$MhKTEmeJTB/Q2YbqLd7uXejgByEuIBb7p0Gy4huu6ktKLNZl38JxC'
  ),
  (
    'Princess',
    'Peach',
    'PriP',
    'peach@nintendo.com',
    '',
    'images/avatars/avatar-3.png',
    true,
    '$2b$10$MhKTEmeJTB/Q2YbqLd7uXejgByEuIBb7p0Gy4huu6ktKLNZl38JxC'
  ),
  (
    'Princess',
    'Daisy',
    'Daisy',
    'daisy@nintendo.com',
    'K1N 9J7',
    'images/avatars/avatar-2.png',
    false,
    '$2b$10$MhKTEmeJTB/Q2YbqLd7uXejgByEuIBb7p0Gy4huu6ktKLNZl38JxC'

  ),
  ('Donkey',
  'Kong',
  'DonK',
  'donkey@nintendo.com',
  '',
  'images/avatars/avatar-5.png',
  true,
  '$2b$10$MhKTEmeJTB/Q2YbqLd7uXejgByEuIBb7p0Gy4huu6ktKLNZl38JxC'
  );